### ISSUE TITLE
Invideous Broken PythonToCppException

### ISSUE THREAD

**Issue by ghost** [TheAssassin/kodi-invidious-plugin#16]
Using kodi 19.4, I get errors when trying to use the app that prevent me from using it

Here's the log
[kodi.log](https://github.com/TheAssassin/kodi-invidious-plugin/files/8530797/kodi.log)

**Comment by 0x004a** [comment]
This Invidious Add-on isn't working for the latest LibreELEC on Raspberry Pi 4.

Not sure why, but looking at repository, seems to be using the instance "invidio.us", which just redirects to a list of instances: https://redirect.invidious.io/

Could it be changed to "yewtu.be" ?  It's an instance that seems to work very well.

**Comment by TheAssassin** [comment]
@0x004a you can already enter your own URL in the settings. I'll change the default to some working instance, though.

Is this even related to @Arndorferd's issue, though?

**Comment by 0x004a** [comment]
> Is this even related to @Arndorferd's issue, though?

No, probably not. Was just a guess.

But same latest version "Kodi 19.4" on LE RPi4, it's not working either. Currently surviving the torture by sharing NewPipe videos to Kore, that shares to Kodi.

**Comment by vanfanel** [comment]
I can confirm this once great plugin does not work at all on Libreelec 10.0.4 (Kodi 19 Matrix) on the Raspberry Pi 4... :(

**Comment by petterreinholdtsen** [comment]
Could it be a missing dependency?  I get this when trying to run the script manually from within LibreELEC:

```
projector:~ # python3 /storage/.kodi/addons/plugin.video.invidious/resources/lib/invidious_addon.py
Traceback (most recent call last):
  File "/storage/.kodi/addons/plugin.video.invidious/resources/lib/invidious_addon.py", line 3, in <module>
    import invidious_plugin
  File "/storage/.kodi/addons/plugin.video.invidious/resources/lib/invidious_plugin.py", line 3, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
projector:~ #
```

**Comment by SethFalco** [comment]
> Could it be changed to "yewtu.be" ? It's an instance that seems to work very well.

It can't be changed to yewtu.be anymore, since it has API access disabled. [[source]](https://api.invidious.io/)

Atm I think an instance like `https://vid.puffyan.us` would be a better choice.

Edit: Ahh, disregard this. In recent commits I can see the default has already been changed to a working instance. It just hasn't been released/published to the Kodi repo.
